---
title: "EDA"
output: html_notebook
---

EDA Analysis for the Satisfaction Dataset

```{r}
# Loading required packages
library(data.table)
library(ggplot2)
library(ggcorrplot)

# Loading data
dt_train <- fread(file = "../data/train.csv", key = "id")
dt_test <- fread(file = "../data/test.csv", key = "id")
dt_full <- rbindlist(
  list(train = dt_train, test = dt_test),
  use.names = TRUE,
  fill = TRUE,
  idcol = "setID"
)

# Meta data
meta <- list(
  match_key = "id",
  setID = "setID",
  target = "satisfaction_level",

  feat_num = c(
    "last_evaluation", 
    "number_project", 
    "average_monthly_hours", 
    "time_spend_company",
    "Work_accident",
    "promotion_last_5years"
  ),
  
  feat_cat = c(
    "salary",
    "package",
    "division"
    
  )
)
```

Assess data quality
```{r}
# Missing value count over all predictors
cnt_missing <- dt_full[, sapply(.SD, function(x) sum(is.na(x))), .SDcols = c(meta$feat_num, meta$feat_cat)]

# No missing data
```

Check distribution
```{r}




```



Check correlation between numeric predictors
```{r}
plt_corr_mat <- function(dt, vars, title = NULL) {
  corr <- cor(dt[, vars, with = FALSE])
  p_mat <- cor_pmat(dt[, vars, with = FALSE])
  plt <- ggcorrplot(
    corr, 
    p.mat = p_mat,
    
    insig = "blank",
    hc.order = TRUE, 
    lab = TRUE,
    type = "lower",
    
    ggtheme = theme_gray,
    outline.col = "white",
    colors = c("#6D9EC1", "white", "#E46726")
  ) + 
    labs(title = title, x = '', y = '')
  
  return(list(mat = corr, plt = plt))
}


# Overall estimation of correlation
corr_train <- plt_corr_mat(dt_train, meta$feat_num, "Corr Mat Train Set Full")
corr_test <- plt_corr_mat(dt_test, meta$feat_num, "Corr Mat Test Set Full")
```
